name: build
on: workflow_dispatch
jobs:
  build:
    name: build
    runs-on: "ubuntu-latest"
    steps:
    - name: delete old releases
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 0
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: checkout
      uses: actions/checkout@master
    - name: make
      uses: cedrickring/golang-action@1.7.0
      env:
        GO111MODULE: "on"
      with:
        args: apt install zip && make
    - name: create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest
        title: latest
        files: dist/*
